ini = { SOI ~ (pair | comment | NEWLINE)* ~ section* ~ EOI }
WHITESPACE = _{ " " | "\t" }

// section
section = { "[" ~ name ~ "]" ~ body }
name = @{ char+ }
char = { ASCII_ALPHANUMERIC | "." | "_" | "/" | " " }
body = { (NEWLINE ~ (pair | comment)?)* }

// key-value pair
pair = { key ~ "=" ~ value }
key = @{ char+ }
value = @{ (char | "=")* }

comment = { indicator ~ value? }
indicator = { "#" | ";" }
